version: '3'

services:
  issuer:
    build: ..
    image: aries-framework-javascript
    container_name: afj-issuer
    command: yarn run-issuer
    # platform: linux/amd64
    volumes:
      - ../samples/issuer.ts:/www/samples/issuer.ts
      # - ../package.json:/www/package.json
    networks:
      - hyperledger
    ports:
      - 4006:4006
    extra_hosts:
      - "docker.host.internal:192.168.0.5"


networks:
  hyperledger: