version: '3'

services:
  mediator:
    build: ..
    image: aries-framework-javascript
    container_name: afj-mediator
    command: yarn run-mediator
    # platform: linux/amd64
    volumes:
      - ../samples/mediator.ts:/www/samples/mediator.ts
      - ../package.json:/www/samples/package.json
    networks:
      - hyperledger
    ports:
      - 6001:6001
      - 7001:7001
    extra_hosts:
      - "docker.host.internal:192.168.0.5"

  # localtunnel:
  #   image: efrecon/localtunnel
  #   restart: on-failure
  #   command:
  #     --local-host mediator --port 6001 --subdomain ariestest1234
  #   links:
  #     - mediator
  #   depends_on:
  #     - mediator

networks:
  hyperledger:
