version: '3'

services:
  demo:
    build: ..
    image: aries-framework-javascript
    container_name: afj-demo
    command: yarn run-demo
    # platform: linux/amd64
    volumes:
      - ../samples/demo.ts:/www/samples/demo.ts
      - ../package.json:/www/package.json
    networks:
      - hyperledger
    # ports:
    #   - 4001:4001
    #   - 3006:3006
    extra_hosts:
      - "docker.host.internal:192.168.0.5"


networks:
  hyperledger: